### ISSUE TITLE
[ERROR] Error: Docusaurus was unable to resolve the "posthog-docusaurus" plugin.

### ISSUE THREAD

**Issue by andrewm4894** [PostHog/posthog-docusaurus#8]
im trying to use the posthog docusarus plugin and getting this error:

```
[ERROR] Error: Docusaurus was unable to resolve the "posthog-docusaurus" plugin. Make sure one of the following packages are installed:
- posthog-docusaurus
- @docusaurus/plugin-posthog-docusaurus
- docusaurus-plugin-posthog-docusaurus
    at resolveModuleName (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\moduleShorthand.js:41:15)
    at normalizeShorthand (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\configs.js:77:60)
    at C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\configs.js:90:66
    at Array.map (<anonymous>)
    at loadPluginConfigs (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\configs.js:90:50)
    at async initPlugins (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\init.js:42:27)
    at async loadPlugins (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\plugins\index.js:26:21)
    at async load (C:\Users\andre\Documents\repos\blog\node_modules\@docusaurus\core\lib\server\index.js:76:58)
```

I can see it in the node_modules and am using it like this
```
  plugins: [
    "posthog-docusaurus",
    ...
    ]
```

https://github.com/andrewm4894/blog/blob/develop/docusaurus.config.js#L98

You ever see this error before?

**Comment by andrewm4894** [comment]
i tried the require.resolve() from here but still fails. https://github.com/facebook/docusaurus/issues/2883
have a feeling its maybe something silly i'm doing around versions or just getting the basics a little wrong

**Comment by mariusandra** [comment]
Turns out version 1.0.4 of the plugin was accidentally published without the `lib/` folder. Version 1.0.5 should fix this.

**Comment by mariusandra** [comment]
We now have 2.0.0 out which should be working fine. Closing the issue.
